#' Create a New R Package
#'
#' Scaffolds a minimal tinyverse-flavored R package: DESCRIPTION with Authors@R,
#' NAMESPACE, .Rbuildignore, NEWS.md, a tinytest entry point, and (optionally)
#' a starter function plus matching test.
#'
#' @param name Package name. Must start with a letter and contain only letters,
#'   numbers, and dots.
#' @param path Directory in which to create the package. The package itself
#'   will be created at `file.path(path, name)`. Default is the current
#'   directory.
#' @param title One-line title in title case (no period).
#' @param description Paragraph describing what the package does.
#' @param author Author full name (e.g., "First Last").
#' @param email Author email address. Also used as the maintainer.
#' @param orcid Optional ORCID identifier (e.g., "0000-0000-0000-0000"). If
#'   supplied, added as `comment = c(ORCID = ...)` in Authors@R.
#' @param license License string for the License field. Default "GPL-3".
#' @param example_fn If TRUE (default), write a starter `R/hello.R` with a
#'   tinyrox-documented `hello()` function and a matching tinytest test.
#'
#' @return Path to the created package directory (invisibly).
#'
#' @export
#'
#' @examples
#' \donttest{
#' tmp <- tempfile("tinypkgr_create_")
#' dir.create(tmp)
#' create_package("mypkg", path = tmp,
#'                author = "First Last",
#'                email = "you@example.com")
#' unlink(tmp, recursive = TRUE)
#' }
create_package <- function(name, path = ".",
                           title = "What The Package Does (One Line, Title Case)",
                           description = "A paragraph describing what the package does.",
                           author, email, orcid = NULL, license = "GPL-3",
                           example_fn = TRUE) {
    if (missing(name) || !is.character(name) || length(name) != 1) {
        stop("'name' must be a single character string", call. = FALSE)
    }
    if (!valid_pkg_name(name)) {
        stop("Invalid package name: ", name,
             ". Must start with a letter and contain only letters, numbers, and dots.",
             call. = FALSE)
    }
    if (missing(author) || !is.character(author) || length(author) != 1) {
        stop("'author' must be a single character string", call. = FALSE)
    }
    if (missing(email) || !is.character(email) || length(email) != 1) {
        stop("'email' must be a single character string", call. = FALSE)
    }

    path <- normalizePath(path, mustWork = TRUE)
    pkg_dir <- file.path(path, name)
    if (file.exists(pkg_dir)) {
        stop("Directory already exists: ", pkg_dir, call. = FALSE)
    }

    dir.create(pkg_dir)
    dir.create(file.path(pkg_dir, "R"))
    dir.create(file.path(pkg_dir, "man"))
    dir.create(file.path(pkg_dir, "tests"))
    dir.create(file.path(pkg_dir, "inst", "tinytest"), recursive = TRUE)

    # DESCRIPTION
    authors_r <- build_authors_r(author, email, orcid)
    desc_lines <- c(
                    paste0("Package: ", name),
                    paste0("Title: ", title),
                    "Version: 0.0.0.9000",
                    "Authors@R:",
                    paste0("    ", authors_r),
                    paste0("Description: ", description),
                    paste0("License: ", license),
                    "Encoding: UTF-8",
                    "Suggests:",
                    "    tinytest"
    )
    writeLines(desc_lines, file.path(pkg_dir, "DESCRIPTION"))

    # NAMESPACE
    ns_lines <- "# Generated by tinyrox: do not edit by hand"
    if (example_fn) {
        ns_lines <- c(ns_lines, "", "export(hello)")
    }
    writeLines(ns_lines, file.path(pkg_dir, "NAMESPACE"))

    # .Rbuildignore
    writeLines(c(
                 "^\\.github$",
                 "^CLAUDE\\.md$",
                 "^cran-comments\\.md$"
        ), file.path(pkg_dir, ".Rbuildignore"))

    # NEWS.md
    writeLines(c(
                 paste0("# ", name, " 0.0.0.9000"),
                 "",
                 "* Initial development version."
        ), file.path(pkg_dir, "NEWS.md"))

    # tests/tinytest.R entry point
    writeLines(c(
                 "if (requireNamespace(\"tinytest\", quietly = TRUE)) {",
                 paste0("  tinytest::test_package(\"", name, "\")"),
                 "}"
        ), file.path(pkg_dir, "tests", "tinytest.R"))

    # Optional starter function and test
    if (example_fn) {
        writeLines(c(
                     "#' Say Hello",
                     "#'",
                     "#' Returns a greeting.",
                     "#'",
                     "#' @param who Name to greet.",
                     "#'",
                     "#' @return A character string.",
                     "#'",
                     "#' @export",
                     "#'",
                     "#' @examples",
                     "#' hello(\"world\")",
                     "hello <- function(who = \"world\") {",
                     "  paste0(\"Hello, \", who, \"!\")",
                     "}"
            ), file.path(pkg_dir, "R", "hello.R"))

        writeLines(c(
                     paste0("expect_equal(", name,
                            "::hello(\"world\"), \"Hello, world!\")"),
                     paste0("expect_equal(", name, "::hello(\"R\"), \"Hello, R!\")")
            ), file.path(pkg_dir, "inst", "tinytest", "test_hello.R"))
    }

    message("Created package '", name, "' at ", pkg_dir)
    invisible(pkg_dir)
}

# Validate a package name against R's naming rules.
valid_pkg_name <- function(name) {
    grepl("^[a-zA-Z][a-zA-Z0-9.]*[a-zA-Z0-9]$", name)
}

# Build an Authors@R person() call as a single-line string.
build_authors_r <- function(author, email, orcid) {
    parts <- strsplit(trimws(author), "\\s+")[[1]]
    if (length(parts) >= 2) {
        given <- paste(parts[-length(parts)], collapse = " ")
        family <- parts[length(parts)]
        person_str <- paste0(
                             "person(\"", given, "\", \"", family,
                             "\", email = \"", email,
                             "\", role = c(\"aut\", \"cre\")"
        )
    } else {
        person_str <- paste0(
                             "person(given = \"", author,
                             "\", email = \"", email,
                             "\", role = c(\"aut\", \"cre\")"
        )
    }
    if (!is.null(orcid)) {
        person_str <- paste0(person_str,
                             ", comment = c(ORCID = \"", orcid, "\")")
    }
    paste0(person_str, ")")
}

